// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxnwFSK4HFjCpHu2ZtTT3dqExVhCiYStM',
    appId: '1:301258608651:web:7c44eda49b214673b0b70e',
    messagingSenderId: '301258608651',
    projectId: 'sipora-73236',
    authDomain: 'sipora-73236.firebaseapp.com',
    databaseURL: 'https://sipora-73236-default-rtdb.firebaseio.com',
    storageBucket: 'sipora-73236.firebasestorage.app',
    measurementId: 'G-ER3FCLJRP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzj8M7eq6RNndOVzc4cuDXIHL6t3N3Dt8',
    appId: '1:301258608651:android:1ac00655ebd9bea4b0b70e',
    messagingSenderId: '301258608651',
    projectId: 'sipora-73236',
    databaseURL: 'https://sipora-73236-default-rtdb.firebaseio.com',
    storageBucket: 'sipora-73236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPlAFZtmwZaPHbAMhJCHoOzTGvkzwjBlI',
    appId: '1:301258608651:ios:b724cf88d6db877ab0b70e',
    messagingSenderId: '301258608651',
    projectId: 'sipora-73236',
    databaseURL: 'https://sipora-73236-default-rtdb.firebaseio.com',
    storageBucket: 'sipora-73236.firebasestorage.app',
    iosClientId: '301258608651-k7f9g998mf70d17aldncbhmtfnmc38qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.sipora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPlAFZtmwZaPHbAMhJCHoOzTGvkzwjBlI',
    appId: '1:301258608651:ios:b724cf88d6db877ab0b70e',
    messagingSenderId: '301258608651',
    projectId: 'sipora-73236',
    databaseURL: 'https://sipora-73236-default-rtdb.firebaseio.com',
    storageBucket: 'sipora-73236.firebasestorage.app',
    iosClientId: '301258608651-k7f9g998mf70d17aldncbhmtfnmc38qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.sipora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxnwFSK4HFjCpHu2ZtTT3dqExVhCiYStM',
    appId: '1:301258608651:web:ecfc9ff32c1e59c5b0b70e',
    messagingSenderId: '301258608651',
    projectId: 'sipora-73236',
    authDomain: 'sipora-73236.firebaseapp.com',
    databaseURL: 'https://sipora-73236-default-rtdb.firebaseio.com',
    storageBucket: 'sipora-73236.firebasestorage.app',
    measurementId: 'G-4LJMF4N8KF',
  );
}
